import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import studentsRouter from "./students.js";
import packsRouter from "./packs.js";
import cardsRouter from "./cards.js";
import collectionsRouter from "./collections.js";
import uploadsRouter from "./uploads.js";
import adminRouter from "./admin.js";
import classesRouter from "./classes.js";
import settingsRouter from "./settings.js";
import mysteryBoxesRouter from "./mystery-boxes.js";
import figurineRaritiesRouter from "./figurine-rarities.js";
import shopRouter from "./shop.js";
import achievementsRouter from "./achievements.js";
import cardRaritiesRouter from "./card-rarities.js";
import cardTypesRouter from "./card-types.js";
import backupsRouter from "./backups.js";
import keepaliveRouter from "./keepalive.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(keepaliveRouter);
router.use(studentsRouter);
router.use(packsRouter);
router.use(cardsRouter);
router.use(collectionsRouter);
router.use(uploadsRouter);
router.use(adminRouter);
router.use(classesRouter);
router.use(settingsRouter);
router.use(mysteryBoxesRouter);
router.use(figurineRaritiesRouter);
router.use(shopRouter);
router.use(achievementsRouter);
router.use(cardRaritiesRouter);
router.use(cardTypesRouter);
router.use(backupsRouter);

export default router;
