// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mythic-effects/ConstellationDrift.tsx": () => import("../components/mockups/mythic-effects/ConstellationDrift.tsx"),
  "./components/mockups/mythic-effects/FloatingEmbers.tsx": () => import("../components/mockups/mythic-effects/FloatingEmbers.tsx"),
  "./components/mockups/mythic-effects/FrostCrystals.tsx": () => import("../components/mockups/mythic-effects/FrostCrystals.tsx"),
  "./components/mockups/mythic-effects/HolographicScan.tsx": () => import("../components/mockups/mythic-effects/HolographicScan.tsx"),
  "./components/mockups/mythic-effects/PrismaticBorder.tsx": () => import("../components/mockups/mythic-effects/PrismaticBorder.tsx"),
  "./components/mockups/mythic-effects/ShimmerSheen.tsx": () => import("../components/mockups/mythic-effects/ShimmerSheen.tsx")
};
